openapi: 3.0.0
info:
  title: ModulePatternAPI
  version: 1.0.0
servers:
  - url: http://localhost:3002
paths:
  /api/student:
    get:
      tags:
        - default
      summary: Get All Students
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create New Student
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                studentName: Carlos
                studentAge: 20
                studentEducationLevel: Highschool
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/student/{studentId}:
    get:
      tags:
        - default
      summary: Get One Student
      parameters:
        - in: path
          name: studentId
          schema:
            type: string
          required: true
          description: ID of the student to get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/student/{studentId}/credits:
    post:
      tags:
        - default
      summary: Complete Student Credits
      parameters:
        - in: path
          name: studentId
          schema:
            type: string
          required: true
          description: ID of the student to get
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                creditsCompleted: 20
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}